apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-service
spec:
  type: LoadBalancer       # Cloud-ready: AWS will provision an ELB/NLB
  selector:
    app: yolo-backend
  ports:
    - protocol: TCP
      port: 5000           # External port exposed via LoadBalancer
      targetPort: 5000     # Container port