apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: yolo-cluster
  region: ap-southeast-2
  version: "1.32"

managedNodeGroups:
  - name: yolo-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20