- name: Build frontend Docker image
  community.docker.docker_image:
    name: "{{ frontend_image_name }}"
    build:
      path: "{{ frontend_path }}"
    state: present
  tags:
    - frontend

- name: Run frontend container
  community.docker.docker_container:
    name: "{{ frontend_container_name }}"
    image: "{{ frontend_image_name }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ frontend_port }}:80"   # Nginx serves on 80 inside container
    networks:
      - name: "{{ network_name }}"
  tags:
    - frontend