- name: Build frontend Docker image
  community.docker.docker_image:
    name: "{{ frontend_container_name }}"
    build:
      path: "{{ app_dir }}/frontend"
    state: present
  tags:
    - frontend

- name: Run frontend container
  community.docker.docker_container:
    name: "{{ frontend_container_name }}"
    image: "{{ frontend_container_name }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ frontend_port }}:80"   # map host port to Nginx container port 80
    networks:
      - name: "{{ docker_network_name }}"
  tags:
    - frontend